# Generated by Django 3.1.3 on 2020-11-07 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Medi', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
