# Generated by Django 3.1.3 on 2020-11-07 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Medi', '0003_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
    ]
