# Generated by Django 3.1.3 on 2020-11-09 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Medi', '0006_appointment'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsRecipients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.DeleteModel(
            name='Yourmodel',
        ),
    ]
