# Generated by Django 3.1.3 on 2020-11-09 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Medi', '0008_article_tags_writter'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_image',
            field=models.ImageField(default=1, upload_to='articles/'),
            preserve_default=False,
        ),
    ]
