# Generated by Django 3.1.3 on 2020-11-10 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Medi', '0009_article_article_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='Writter',
        ),
        migrations.RemoveField(
            model_name='article',
            name='tags',
        ),
        migrations.DeleteModel(
            name='tags',
        ),
        migrations.DeleteModel(
            name='Writter',
        ),
    ]
