# Generated by Django 3.1.3 on 2020-11-11 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Medi', '0010_auto_20201110_1121'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
