# Generated by Django 3.1.3 on 2020-11-12 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Medi', '0011_delete_profile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Article',
            new_name='News_showbiz',
        ),
    ]
